site:               gurungkshitij.github.io
title:               Kshitij Gurung 
bio:                <font size = 1> I am a motivated learner with a great passion for data science and analytics. I recently graduated from St. Olaf College with a Bachelor in Economics, Mathematics, Statistics and Data Science. I enjoy working with data and producing information that convey a compelling story. My interests lie in the intersection of data science and health care, sports & exercise, and econometrics. Besides my professional work, I love speding time playing soccer, working out (powerlifting), cooking, hair cutting, and Singnig.</font>  
description:        "Welcome!"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/kg.jpg'
background:         https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F28%2F2020%2F03%2F26%2Fhimalayas-eastern-nepal-milky-way-SPRINGSKY0320.jpg
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://gurungkshitij.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email: kshitijgurung09@gmail.com
#twitter:            username
#facebook:           kshitij.gurung.56
github-url:         gurungkshitij
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          kshitij-gurung-7866ab136
#xing:              username
instagram:          kshitij.gurung
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
